### ISSUE TITLE
pix2pix broken

### ISSUE THREAD

**Issue by db0** [hlky/nataili#144]
Looks like everyone is encountering this error in the latest update

```
ERROR      | 2023-02-18 18:20:55.909728 | worker.jobs.stable_diffusion:start_job:304 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'REDACTED', 'height': 512, 'width': 512, 'seed': '385798015', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 30, 'sampler_name': 'k_euler_karras', 'cfg_scale': 7.0, 'denoising_strength': 0.4, 'init_img': <PIL.Image.Image image mode=RGB size=404x404 at 0x7F85218F8C40>, 'request_type': 'img2img', 'model': 'pix2pix'}
TRACE      | 2023-02-18 18:20:55.910278 | worker.jobs.stable_diffusion:start_job:310 - Traceback (most recent call last):
  File "/home/db0/AI-Horde-Worker/worker/jobs/stable_diffusion.py", line 298, in start_job
    generator.generate(**gen_payload)
  File "/home/db0/AI-Horde-Worker/conda/envs/linux/lib/python3.8/site-packages/nataili/util/cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "/home/db0/AI-Horde-Worker/conda/envs/linux/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/db0/AI-Horde-Worker/conda/envs/linux/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/db0/AI-Horde-Worker/conda/envs/linux/lib/python3.8/site-packages/nataili/stable_diffusion/compvis.py", line 696, in generate
    samples_ddim, _ = sampler.sample(
  File "/home/db0/AI-Horde-Worker/conda/envs/linux/lib/python3.8/site-packages/ldm/models/diffusion/kdiffusion.py", line 160, in sample
    if conditioning.shape[1] != unconditional_conditioning.shape[1]:
AttributeError: 'dict' object has no attribute 'shape'
```

**Comment by hlky** [comment]
` in the latest update`
Since which update? Nothing related has changed in v0.2.46

**Comment by hlky** [comment]
`if conditioning.shape[1] != unconditional_conditioning.shape[1]:`
This was introduced by @ResidentChief in [v0.2.45](https://github.com/hlky/nataili/commit/7b66a0a98b83ed9848be41e13f1cd38fcc9fc412#diff-bc91097826c55f127641d8f46c0e307db4adc40c0142c3ca899234b601678e7e)

**Comment by hlky** [comment]
@db0 

fixed in v0.2.47

![00000-50_k_lms_2417765648_make-the-girl-a-brunette](https://user-images.githubusercontent.com/106811348/219938925-d48e464a-86e2-42bc-99e7-04b536f325e0.jpg)

**Comment by jug-dev** [comment]
Is this related to this fix? https://github.com/hlky/nataili/issues/145

**Comment by ResidentChief** [comment]
Yeah it will be - itll require another line matching the
cond[“c_crossattn”] and the un_cond[“c_crossattn”]
