### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by jug-dev** [hlky/nataili#154]
nataili 0.2.6969

I apologize if this is a horde worker bug, I report it here due to the nature of the stack trace.

Since updating today from nataili 0.2.50 I see some frequent exceptions in the horde worker. Reproduced below. Non of my horde config changed, just updated the horde worker code and updated the runtime environment (including nataili)

Seems to only occur with some prompts.

ERROR      | 2023-02-22 22:34:17.888286 | worker.jobs.stable_diffusion:start_job:312 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'two brunettes sucking cock, blowjob, nice penis, ### weird mouth,weird teeth,incorrect anatomy, bad anatomy, ugly, odd, hideous, unsightly, extra limbs, poorly drawn, poorly drawn face, bad drawing, sketch, disfigured, cropped, out of frame,fully clothed,sad,agony,pain,small boobs,cut off,trimmed,headpiece, head necklace,out of frame, malformed,hideous face, too many limbs, missing fingers, too many fingers, text, bad drawing, sketch, incorrect anatomy, hideous, unsightly, extra limbs, poorly drawn, poorly drawn face, disfigured, cropped', 'height': 512, 'width': 1024, 'seed': '981863828', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 20, 'sampler_name': 'k_euler_a', 'cfg_scale': 8.5, 'denoising_strength': 0.75, 'control_type': 'canny', 'init_img': <PIL.Image.Image image mode=RGB size=1024x512 at 0x20E5365C580>, 'request_type': 'img2img', 'model': 'Deliberate'}

```
TRACE      | 2023-02-22 22:34:17.888286 | worker.jobs.stable_diffusion:start_job:318 - Traceback (most recent call last):
  File "F:\AI\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 306, in start_job
    generator.generate(**gen_payload)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 864, in generate
    cond["c_crossattn"][0], un_cond["c_crossattn"][0] = fix_mismatched_tensors(
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\prompt_weights.py", line 34, in fix_mismatched_tensors
    conditioning = torch.cat((conditioning, paddings), dim=1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_cat)
```

**Comment by AlRlC** [comment]
1 worker thread, k_euler_a sampler
```
ERROR      | 2023-02-22 14:04:24.904817 | worker.jobs.stable_diffusion:start_job:312 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'cat ### weird mouth,weird teeth,incorrect anatomy, bad anatomy, ugly, odd, hideous, unsightly, extra limbs, poorly drawn, poorly drawn face, bad drawing, sketch, disfigured, cropped, out of frame,fully clothed,sad,agony,pain,small boobs,cut off,trimmed,headpiece, head necklace,out of frame, malformed,hideous face, too many limbs, missing fingers, too many fingers, text, bad drawing, sketch, incorrect anatomy, hideous, unsightly, extra limbs, poorly drawn, poorly drawn face, disfigured, cropped', 'height': 768, 'width': 512, 'seed': '1211562620', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 20, 'sampler_name': 'k_euler_a', 'cfg_scale': 8.5, 'denoising_strength': 0.75, 'control_type': 'canny', 'init_img': <PIL.Image.Image image mode=RGB size=512x768 at 0x2BD079B9660>, 'request_type': 'img2img', 'model': 'Deliberate'}
TRACE      | 2023-02-22 14:04:24.907817 | worker.jobs.stable_diffusion:start_job:318 - Traceback (most recent call last):
  File "C:\Users\Airic\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 306, in start_job
    generator.generate(**gen_payload)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 864, in generate
    cond["c_crossattn"][0], un_cond["c_crossattn"][0] = fix_mismatched_tensors(
  File "C:\Users\Airic\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\prompt_weights.py", line 34, in fix_mismatched_tensors
    conditioning = torch.cat((conditioning, paddings), dim=1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_cat)


```

**Comment by db0** [comment]
Looks like a negprompt + controlnet issue. Hlky is fixing. Disable controlnet until then
