### ISSUE TITLE
UnboundLocalError: local variable 'sampler' referenced before assignment

### ISSUE THREAD

**Issue by jug-dev** [hlky/nataili#155]
nataili 0.2.69

Exception experienced since this new version

ERROR      | 2023-02-22 14:43:39.162407 | worker.jobs.stable_diffusion:start_job:302 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'an ultra realistic photo of a business woman using a hi-tech futuristic digital style user interface, Hyperrealistic, masterpiece, magic hour, high contrast, sharp focus, hyperrealism, user experience, UX design, UI design, meta verse, software, hud element ultra-realistic, ultra resolution, highly detailed', 'height': 576, 'width': 576, 'seed': '2244181946', 'tiling': False, 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 50, 'sampler_name': 'dpmsolver_karras', 'cfg_scale': 8.0, 'hires_fix': False, 'request_type': 'txt2img', 'model': 'Dreamlike Photoreal'}

Stack trace:

```
TRACE      | 2023-02-22 14:43:39.162407 | worker.jobs.stable_diffusion:start_job:308 - Traceback (most recent call last):
  File "F:\AI\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 296, in start_job
    generator.generate(**gen_payload)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\cast.py", line 29, in wrap
    return amp.autocast(device_type="cuda", dtype=dtype)(no_grad()(func))(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 393, in generate
    sampler = create_sampler_by_sampler_name(model)
  File "F:\AI\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\stable_diffusion\compvis.py", line 364, in create_sampler_by_sampler_name
    return sampler
UnboundLocalError: local variable 'sampler' referenced before assignment
```

**Comment by hlky** [comment]
Sampler does not exist. Bad request sent by Stable Horde.
